// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace Nyota
{

// Ability
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_LightAttack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_LeftLightAttack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_RightLightAttack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateOnGive);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WaterBall);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WaterBubble);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Grab);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Grab_Slam);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Grab_VortexGrip);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_State)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_State_Grabbing)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_State_Grabbing_Slam)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_State_Grabbing_VortexGrip)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_init);

// Event
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_AttackStart)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_AttackEnd)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_LightAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_ShootWaterBall)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_WaterBubbleEnd)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_StartGrabTrace)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_StopGrabTrace)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_GrabEnd)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_GrabSlam)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_GrabVortexGrip)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_ApplyDamage)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_HasGrabbedEnemy)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_HitReact)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_BoarLanded)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_PickUp)

} // namespace Nyota
